### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by vamWu** [RuijieZhu94/MotionGS#1]
Thank you for your outstanding work. 

May I know your code release plan? Will you open source all the code or only part of it? 
Will any core code be released before the CVPR 2024 deadline?

**Comment by RuijieZhu94** [comment]
Hi @vamWu , thank you for your interest in our work!

We plan to gradually clean up and release the full code after the CVPR 2024 deadline. Unfortunately, before then, we may not have the bandwidth to maintain this repository. I appreciate your understanding and patience.

Feel free to keep an eye on this repository for updates.

**Comment by vamWu** [comment]
Thank you for your response. 
I'll be keeping an eye out to learn more about your great work!
