### ISSUE TITLE
question about motion flow

### ISSUE THREAD

**Issue by tb2-sy** [RuijieZhu94/MotionGS#2]
Thanks for your nice work! In sec 4.2 of the paper, it is mentioned that the motion flow is rendered under the camera at time t+1, but why is it rendered under the camera at time t in Appendix A.1?

**Comment by RuijieZhu94** [comment]
Thanks for your insightful observation! We appreciate your interest in our work. Theoretically, the camera flow and motion flow vectors must be combined to produce the optical flow, so they naturally exist in different reference frames. However, in our experiments, we found that rendering the motion flow at time t+1 did not lead to better results. This approach requires using warping operations, which are essentially interpolation approximations. Therefore, we simplified the computation in our experiments by using scalar subtraction instead. As a result, rendering the motion flow at time t is sufficient.

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please feel free to open another issue.
