### ISSUE TITLE
reuse the optical flow maps

### ISSUE THREAD

**Issue by zdrac** [RuijieZhu94/MotionGS#3]
Thanks for your wonderful work! In your paper it is mentioned that "During the first epoch of training, we calculate the optical flow
for all adjacent frame pairs, resulting in a total of N − 1 optical flow maps. In subsequent epochs, we do not reshuffle the image sequence, allowing us to reuse the optical flow maps calculated in the first epoch. "

Is this also the case for gaussianflow computation in your work? Or is only optical flow multiplexed in each loop?
 I tried to reuse the gaussianflow, that is, each time through the loop, I saved the render_pkg of the next iteration and used it as the first render_pkg call in the next iteration. But RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [36864, 3]] is at version 1;  expected version 0 instead. Hint:  the backtrace further above shows the operation that failed to compute its gradient. The variable in question was  changed in there or anywhere later. 
How can I solve this problem？
My code is as follows:
for viewpoint_cam in viewpoint_cams:
                        
            if last_viewpoint_cam is None:
                print("First iteration: Calculating flow between two new frames.") 
                time_k = viewpoint_cam.time
                cam_id = viewpoint_cam.cam_id
                time_target = round(time_k * 270) + 1
                cam_id_list = [cam for cam in viewpoint_stack if cam.cam_id == cam_id]
                times = [round(cam.time * 270) for cam in cam_id_list]
                idx = bisect.bisect_left(times, time_target)
                if idx < len(cam_id_list) and times[idx] == time_target:
                    viewpoint_cam_k1 = cam_id_list[idx]
                else:
                    viewpoint_cam_k1 = None
                render_pkg = render(viewpoint_cam, gaussians, pipe, background, stage=stage,cam_type=scene.dataset_type,iteration=iteration)
                image, viewspace_point_tensor, visibility_filter, radii, offset = render_pkg["render"], render_pkg["viewspace_points"], render_pkg["visibility_filter"], render_pkg["radii"], render_pkg["offset"]              
                proj_2D_t_1 = render_pkg["proj_means_2D"]
                gs_per_pixel = render_pkg["gs_per_pixel"].long()
                weight_per_gs_pixel = render_pkg["weight_per_gs_pixel"]
                x_mu = render_pkg["x_mu"]
                cov2D_inv_t_1 = render_pkg["conic_2D"].detach()

                render_pkg_t2 = render(viewpoint_cam_k1, gaussians, pipe, background, stage=stage,cam_type=scene.dataset_type,iteration=iteration)
                last_viewpoint_cam = viewpoint_cam_k1  
                prev_render_pkg = render_pkg_t2
                
            else:
                viewpoint_cam = last_viewpoint_cam
                time_k = viewpoint_cam.time
                cam_id = viewpoint_cam.cam_id
                time_target = round(time_k * 270) + 1
                cam_id_list = [cam for cam in viewpoint_stack if cam.cam_id == cam_id]
                times = [round(cam.time * 270) for cam in cam_id_list]
                idx = bisect.bisect_left(times, time_target)
                if idx < len(cam_id_list) and times[idx] == time_target:
                    viewpoint_cam_k1 = cam_id_list[idx]
                else:
                    viewpoint_cam_k1 = None
                render_pkg_t2 = render(viewpoint_cam_k1, gaussians, pipe, background, stage=stage,cam_type=scene.dataset_type,iteration=iteration)

                image, viewspace_point_tensor, visibility_filter, radii, offset = prev_render_pkg["render"], prev_render_pkg["viewspace_points"], prev_render_pkg["visibility_filter"], prev_render_pkg["radii"], prev_render_pkg["offset"]
                gs_per_pixel = prev_render_pkg["gs_per_pixel"].long()
                weight_per_gs_pixel = prev_render_pkg["weight_per_gs_pixel"]
                x_mu = prev_render_pkg["x_mu"]
                cov2D_inv_t_1 = prev_render_pkg["conic_2D"].detach()
                
                last_viewpoint_cam = viewpoint_cam_k1 
                #prev_render_pkg = {key: value.clone() for key, value in render_pkg_t2.items()}  
                prev_render_pkg = render_pkg_t2

**Comment by RuijieZhu94** [comment]
Thanks for your interest in our work! Indeed, only the optical flow needs to be reused, as it serves as a pseudo-label in this framework, while the Gaussian flow is the quantity we predict.

**Comment by zdrac** [comment]
Thanks for your answer! By the way, if you get frame k, how do you get frame k+1 in the same loop? Do you sort the viewpoint_stack ahead of time before the iterations? And if your method is applied to a fixed multi-camera scene like the Dynerf dataset, does optical flow become equivalent to motion flow, since the cameras are stationary?

**Comment by RuijieZhu94** [comment]
Q: Do you sort the viewpoint_stack ahead of time before the iterations?
A: Exactly.

Q: And if your method is applied to a fixed multi-camera scene like the Dynerf dataset, does optical flow become equivalent to motion flow, since the cameras are stationary?
A: If you're only using a single camera, it's true that you could directly equate optical flow with motion flow. Unfortunately, using just one camera is always insufficient for accurate reconstruction. In the Dynerf dataset, the training views are captured from multiple fixed camera positions, and in the view stack, they are unordered, so this issue cannot be handled in a straightforward manner.

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please feel free to open another issue.
