### ISSUE TITLE
Regarding iterative training

### ISSUE THREAD

**Issue by vamWu** [RuijieZhu94/MotionGS#4]
Regarding iterative training, you mentioned in Section 4.3 and Appendix A.2 that to accelerate the process, each iteration leverages the second frame (render_pkg2) from the previous iteration as the initial frame (render_pkg1) for the current iteration.

I encountered a similar issue to "issue3" #3  in my training.

I think the reason for this is the adaptive Gaussian densification performed when calculating the L1 loss and gradient backpropagation after each iteration. This adaptation changes the number of Gaussians (gs) in the representation.

As a result, directly reusing the previous iteration’s second frame, render_pkg2, as render_pkg1 for the current iteration, leads to a dimensional mismatch when calculating GaussianFlow between this reused frame and the new second frame (render_pkg2) of the current iteration.

To address this issue, I have two simple ideas:

1. After adaptive Gaussian densification (where the gs count changes), I could re-render render_pkg2 using the previous frame’s viewpoint and the updated GS parameters, generating a new render_pkg1 for the current iteration. Then, this updated render_pkg1 could be used with the current iteration’s render_pkg2 for GaussianFlow calculation. However, this approach seems slow and may introduce other issues.

2. From carefully reviewing your paper, it appears you may have mitigated this issue by freezing all gs parameters except for the camera's motion flow during optimization. This avoids Gaussian pruning or densification, thereby keeping the gs count consistent and enabling efficient GaussianFlow computation.

I'm not sure if I'm understanding this correctly, or if there are other ways to iterate quickly and compute the correct GaussianFlow.

**Comment by RuijieZhu94** [comment]
I actually don't fully understand your question...

Are you asking about the mechanics of data sampling?

```
        viewpoint_cam1 = viewpoint_stack.pop(0)
        viewpoint_cam2 = viewpoint_stack[0]
```

**Comment by vamWu** [comment]
Thank you for your time and response. I apologize for not being clear in my initial question. Here is what I’d like to ask:

1. In section 4.3 of the main text and appendix A.2, you mentioned: “In each iteration, we read two frames and calculate the optical flow between them. To enhance efficiency, the second image from the last iteration is used as the first image in the current iteration.” My understanding of this is that for the current time \(T\) and its corresponding Frame \(T\), you would use the `previous_render_pkg` from Frame \(T-1\) alongside the `current_render_pkg` from Frame \(T\) to calculate the Gaussian Flow between Frame \(T\) and Frame \(T-1\).

However, I am encountering dimension mismatch issues in my implementation. 
``` python
File "train.py", line 282, in scene_reconstruction
    B_t_2_B_inv_t_1 = torch.bmm(B_t_2, B_inv_t_1)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [37955, 2] but got: [37315, 2].
```

After analyzing, I think this might be due to changes in the number of GS after backpropagation(Use GaussianFlow loss and L1 Loss), especially after the pruning or densification operations in the previous iteration. This results in a mismatch for the `previous_render_pkg` in the subsequent iteration when calculating the GaussianFlow. 

Upon reviewing your paper more closely, I noticed that you seem to freeze the gradients of all Gs while using Flow loss, which should prevent changes in the number of Gs. I’ve adjusted my code based on this understanding and resolved the dimension mismatch error, but I’m not entirely sure if this approach aligns with your intended method.

2. In Appendix A.2, you mentioned “reading image sequences in a randomly shuffled order.” Does this mean that frames could be temporally far apart (e.g., Frame \(T\) and Frame \(T+10\))?  Would this potentially make it more challenging to calculate the Optical Flow, given that Optical Flow generally assumes close proximity between frames in time?

**Comment by RuijieZhu94** [comment]
1. "In each iteration, we read two frames and calculate the optical flow between them." This refers to the calculation of optical flow, not Gaussian flow. For example, given frames 1, 2, 3, 4, 5, we calculate the optical flow $flow_{12}, flow_{23}, flow_{34}, flow_{45}$. 

Motion flow = Optical flow - Camera flow, serving as our pseudo ground truth.

To align with the motion flow, we design the Gaussian flow formulation. Consequently, we use two `render_pkg` components to compute the Gaussian flow. Here is the code (from Gaussianflow):
```
def calculate_gs_flow(gs_per_pixel, weight_per_gs_pixel, next_conic_2D, conic_2D_inv, proj_2D, next_proj_2D, x_mu):
    conic_2D_inv = conic_2D_inv.detach() # K 3
    gs_per_pixel = gs_per_pixel.long() # K H W
    # valid_mask = ~(gs_per_pixel < 0).any(dim=0) # H W
    conv_conv = torch.zeros([conic_2D_inv.shape[0], 2, 2], device=conic_2D_inv.device) # K 2 2
    conv_conv[:, 0, 0] = next_conic_2D[:, 0] * conic_2D_inv[:, 0] + next_conic_2D[:, 1] * conic_2D_inv[:, 1]
    conv_conv[:, 0, 1] = next_conic_2D[:, 0] * conic_2D_inv[:, 1] + next_conic_2D[:, 1] * conic_2D_inv[:, 2]
    conv_conv[:, 1, 0] = next_conic_2D[:, 1] * conic_2D_inv[:, 0] + next_conic_2D[:, 2] * conic_2D_inv[:, 1]
    conv_conv[:, 1, 1] = next_conic_2D[:, 1] * conic_2D_inv[:, 1] + next_conic_2D[:, 2] * conic_2D_inv[:, 2]

    # isotropic gs flow
    # flow_per_pixel = next_proj_2D[gs_per_pixel] - proj_2D[gs_per_pixel].detach() # K H W 3

    # anisotropic gs flow
    conv_multi = (conv_conv[gs_per_pixel] @ x_mu.permute(0,2,3,1).unsqueeze(-1).detach()).squeeze() # K H W 2
    flow_per_pixel = (conv_multi + next_proj_2D[gs_per_pixel] - proj_2D[gs_per_pixel].detach() - x_mu.permute(0,2,3,1).detach()) # K H W 2

    weight_per_gs_pixel = weight_per_gs_pixel / (weight_per_gs_pixel.sum(dim=0, keepdim=True) + 1e-7) # K H W
    flow_gs = torch.einsum("khw, khwa -> ahw", [weight_per_gs_pixel.detach(), flow_per_pixel]) # 2 H W
    return flow_gs
    # return flow_gs * valid_mask.float().detach()
```

2. Exactly. We have noticed this issue, but we are currently unsure of how to resolve it.

**Comment by vamWu** [comment]
Thank you for your timely answer, I have no more questions at the moment.
