### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by OrangeSodahub** [RuijieZhu94/MotionGS#5]
Hi, it's an excellent work. Want to know the time plan to release codes

**Comment by jiangguangan** [comment]
I would like to consult you first about how the Gaussian flow is obtained？That's key to what I'm doing.Thank you very much for your work

**Comment by RuijieZhu94** [comment]
> I would like to consult you first about how the Gaussian flow is obtained？That's key to what I'm doing.Thank you very much for your work

Please see https://github.com/RuijieZhu94/MotionGS/issues/4#issuecomment-2447232196.

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please feel free to open another issue.
